### ISSUE TITLE
perf: script update

### ISSUE THREAD

**Issue by nareshkamboju** [Linaro/meta-lkft#140]
After updating core sight configs into our builds. The perf test case
seems to be old. I can see 72 test cases instead of 74 test cases.

Here is the command to varify

 - perf test list

ref:
Introduce CoreSight support to LKFT
https://projects.linaro.org/browse/LKQ-268

- Naresh

**Comment by mrchapp** [comment]
Closed by https://github.com/Linaro/meta-lkft/pull/143
